pointcloud_to_laserscan:
  target_frame: "base_link"  # Frame de referência
  transform_tolerance: 0.01  # Tolerância de transformação
  min_height: -0.1           # Altura mínima para considerar pontos
  max_height: 0.1            # Altura máxima para considerar pontos
  angle_min: -1.57           # Ângulo mínimo do laser
  angle_max: 1.57            # Ângulo máximo do laser
  angle_increment: 0.0087      # Incremento de ângulo
  scan_time: 0.3333             # Tempo de varredura
  range_min: 0.45             # Distância mínima
  range_max: 4           # Distância máxima
  use_inf: true              # Usar valores inf para limites
  inf_epsilon: 1.0